// Generated by https://quicktype.io

import { NotionCreatedTime, NotionDate, NotionMultiSelect, NotionName, NotionNumber, NotionRichText, NotionSelect, NotionText, NotionUrl } from "./notion"

export interface MediaListEntry {
    "Hype / Score":    NotionNumber
    Progress:          NotionNumber
    "Author / Studio": NotionRichText
    Type:              NotionMultiSelect
    "Dated Added":     NotionCreatedTime
    Status:            NotionSelect
    Link:              NotionUrl
    Total:             NotionNumber
    English:           NotionRichText
    "Date Completed":  NotionDate
    Name:              NotionName
}